version: "3.8"

services:
  web:
    container_name: sortlink
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6004:80"
    volumes:
      - ./:/var/www/html
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=your-database
      - MYSQL_USER=your-user
      - MYSQL_PASSWORD=your-user
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mariadb:10.6
    container_name: sortlink_db
    platform: linux/arm64
    environment:
      - MARIADB_DATABASE=your-database
      - MARIADB_USER=your-user
      - MARIADB_PASSWORD=your-password
      - MARIADB_ROOT_PASSWORD=your-root-password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: "--default-authentication-plugin=mysql_native_password"
    restart: unless-stopped

  adminer:
    image: adminer:4.8.1
    container_name: sortlink_adminer
    environment:
      - ADMINER_DEFAULT_SERVER=db
      - ADMINER_DESIGN=dracula
      - ADMINER_PLUGINS=tables-filter tinymce
    ports:
      - "4004:8080"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  mysql_data:
